[package]
name = "ant-quic"
version = "0.1.1"
edition = "2021"
rust-version = "1.74.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dirvine/ant-quic"
description = "QUIC transport protocol with advanced NAT traversal for P2P networks"
keywords = ["quic", "nat-traversal", "p2p", "autonomi", "networking"]
categories = ["network-programming", "asynchronous"]

[features]
# NOTE: Please keep this in sync with the feature list in `.github/workflows/codecov.yml`, see
# comment in that file for more information.
default = ["rustls-ring", "log", "bloom"]
aws-lc-rs = ["dep:aws-lc-rs", "aws-lc-rs?/aws-lc-sys", "aws-lc-rs?/prebuilt-nasm"]
aws-lc-rs-fips = ["aws-lc-rs", "aws-lc-rs?/fips"]
# Enables BloomTokenLog, and uses it by default
bloom = ["dep:fastbloom"]
# For backwards compatibility, `rustls` forwards to `rustls-ring`
rustls = ["rustls-ring"]
# Enable rustls with the `aws-lc-rs` crypto provider
rustls-aws-lc-rs = ["dep:rustls", "rustls?/aws-lc-rs", "aws-lc-rs"]
rustls-aws-lc-rs-fips = ["rustls-aws-lc-rs", "aws-lc-rs-fips"]
# Enable rustls with the `ring` crypto provider
rustls-ring = ["dep:rustls", "rustls?/ring", "ring"]
ring = ["dep:ring"]
# Enable rustls ring provider and direct ring usage
# Provides `ClientConfig::with_platform_verifier()` convenience method
platform-verifier = ["dep:rustls-platform-verifier"]
# Configure `tracing` to log events via `log` if no `tracing` subscriber exists.
log = ["tracing/log"]
# Enable rustls logging
rustls-log = ["rustls?/logging"]
# Enable qlog support
__qlog = ["dep:qlog"]

[dependencies]
arbitrary = { version = "1.0.1", features = ["derive"], optional = true }
aws-lc-rs = { version = "1.9", default-features = false, optional = true }
bytes = "1"
fastbloom = { version = "0.12", optional = true }
lru-slab = "0.1.2"
qlog = { version = "0.15.2", optional = true }
rustc-hash = "2"
rand = "0.9"
ring = { version = "0.17", optional = true }
rustls = { version = "0.23.5", default-features = false, features = ["std"], optional = true }
rustls-platform-verifier = { version = "0.6", optional = true }
slab = "0.4.6"
thiserror = "2.0.3"
tinyvec = { version = "1.1", features = ["alloc"] }
tracing = { version = "0.1.10", default-features = false, features = ["std"] }

# Dependencies for ant-quic binary
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.28.1", features = ["full"] }
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }
local-ip-address = "0.6"
unicode-width = "0.1"
hex = "0.4"
four-word-networking = "1.2"

# Feature flags & dependencies for wasm
# wasm-bindgen is assumed for a wasm*-*-unknown target
[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
ring = { version = "0.17", features = ["wasm32_unknown_unknown_js"] }
getrandom = { version = "0.3", default-features = false, features = ["wasm_js"] }
rustls-pki-types = { version = "1.7", features = ["web"] } # only added as dependency to enforce the `web` feature for this target
web-time = "1"

[dev-dependencies]
assert_matches = "1.1"
hex-literal = "1"
rand_pcg = "0.9"
rcgen = "0.14"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }
lazy_static = "1"
wasm-bindgen-test = { version = "0.3.45" }

[lints.rust]
# https://rust-fuzz.github.io/book/cargo-fuzz/guide.html#cfgfuzzing
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }

# NAT traversal examples (for reference and testing)
[[example]]
name = "nat_simulation"
path = "examples/nat_simulation.rs"

# Main binary - unified P2P node with automatic coordinator services
[[bin]]
name = "ant-quic"
path = "src/bin/ant-quic.rs"

[package.metadata.docs.rs]
# all non-default features except fips (cannot build on docs.rs environment)
features = ["rustls-aws-lc-rs", "rustls-ring", "platform-verifier", "log", "rustls-log"]