name: Coverage

on:
  push:
    branches: ['master', '0.8.x']

jobs:
  coverage:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30  # Add timeout to prevent hanging
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2  # Add caching to speed up builds
      - shell: bash
        # Run llvm-cov _without_ the "aws-lc-rs-fips" or "rustls-aws-lc-rs-fips" features, since
        # they have complex build requirements:
        #     https://github.com/aws/aws-lc/blob/3263ce2a553e4e917217fb487f8c6f488fcb1866/BUILDING.md#build-prerequisites
        #
        # This list of features was determined using:
        #     cargo metadata --format-version 1 --no-deps \
        #       | jq -r ' .packages[].features | keys[]' \
        #       | sort -u \
        #       | grep -vFx -e 'default' -e 'aws-lc-rs-fips' -e 'rustls-aws-lc-rs-fips' \
        #       | paste -sd ',' -
        run: |
          # Run coverage with reduced feature set and ignore stress tests
          cargo llvm-cov \
            --features="rustls-ring" \
            --workspace --lcov --output-path lcov.info \
            -- --skip stress
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
