name: Comprehensive NAT Traversal Testing

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  nat-traversal-tests:
    name: NAT Traversal Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run NAT Traversal Frame Tests
      run: cargo test --test nat_traversal_frame_tests --features "network-discovery" -- --nocapture
      
    - name: Run Frame Encoding Tests
      run: cargo test --test frame_encoding_tests --features "network-discovery" -- --nocapture
      
    - name: Run NAT Traversal Simulation Tests
      run: cargo test --test nat_traversal_simulation --features "network-discovery" -- --nocapture

  multi-platform-tests:
    name: Platform Compatibility Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run Platform Discovery Tests
      run: |
        cargo test --test discovery --features "network-discovery" -- --nocapture
        cargo test candidate_discovery --lib --features "network-discovery" -- --nocapture

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run Integration Test Suite
      run: |
        echo "Running comprehensive integration tests..."
        cargo test --test nat_simulation --features "network-discovery" -- --nocapture
        cargo test --test connection_success_rates --features "network-discovery" -- --nocapture
        cargo test --test address_discovery_integration --features "network-discovery" -- --nocapture

  performance-benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run Performance Benchmarks
      run: |
        echo "Running performance benchmarks for NAT traversal..."
        cargo bench --bench nat_traversal --features "network-discovery"
        cargo bench --bench candidate_discovery --features "network-discovery"
        cargo bench --bench address_discovery_bench --features "network-discovery"

  security-validation:
    name: Security Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run Security Linting
      run: |
        echo "Running security validation..."
        cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used -W clippy::expect_used
        
    - name: Check for Security Issues
      run: |
        cargo audit --deny warnings || echo "::warning::Security audit found issues. Please review the output above."

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [nat-traversal-tests, multi-platform-tests, integration-tests, performance-benchmarks, security-validation]
    if: always()
    steps:
    - name: Test Summary
      run: |
        echo "## NAT Traversal Comprehensive Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Categories Completed:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ NAT Traversal Frame Tests" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Multi-Platform Compatibility Tests (Windows, Linux, macOS)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Integration Tests" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Performance Benchmarks" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Security Validation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Coverage:" >> $GITHUB_STEP_SUMMARY
        echo "- NAT traversal frame encoding/decoding" >> $GITHUB_STEP_SUMMARY
        echo "- Multi-node coordination across different NAT types" >> $GITHUB_STEP_SUMMARY
        echo "- Platform-specific network interface discovery" >> $GITHUB_STEP_SUMMARY
        echo "- Connection establishment success rates" >> $GITHUB_STEP_SUMMARY
        echo "- Address discovery integration" >> $GITHUB_STEP_SUMMARY
        echo "- Security validation with clippy" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All comprehensive NAT traversal tests completed! 🎉" >> $GITHUB_STEP_SUMMARY